services:
  web:
    container_name: gando-pages
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/certs:/etc/nginx/certs:rw
    env_file:
      - .env
    restart: always
